# ================= 监控中心 公用配置 开始 =====================
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    bus-refresh:
      enabled: true
# ================= 监控中心 公用配置 结束=====================